#+latex_class: luckypdf
#+language: fr
#+title: Cisco (RESIR2) - Lucky Summary
#+author: Sm!le42

* Composants réseaux
** <<Network>>Network
Un réseau est un *ensemble inter-connecté*, fait de composants autorisant la *circulation de flux* ou d'éléments finis.

\textcolor{luckydarkgray}{(Ensemble de relations)}
** Rôle d'hôte
*** <<Host>>Hôtes ou périphériques finaux
Parfois appelés *clients*, ce sont des *ordinateurs connectés* à un réseau et qui participent directement aux communications transmises sur le réseau.

\textcolor{luckydarkgray}{(Ex: Ordinateur, téléphone, tablette, imprimante...)}
*** <<IPAddress>>Adresse IP
*Numéro* qui *identifie* [[Host][l'hôte]] et le [[Network][réseau]] auquel l'hôte est connecté.
**** *IPv4:*
/Adresses IP/ codées sur *32 bits*. Au maximum 2^{32} adresses /(soit 4 294 967 296)/ peuvent donc être attribuées simultanément en théorie (en pratique, un certain nombre ne sont pas utilisables).

Une /adresse IPv4/ est représentée sous la forme de *quatre nombres entiers* séparés par des points. \textcolor{luckydarkgray}{(Ex: 193.43.55.67)}

Chacun des nombres représente *un octet*. La plage d'attribution s'étend de /0.0.0.0/ à /255.255.255.255/, sachant qu'il existe des contraintes empêchant l'utilisation de certaines adresses (réservée, masque, broadcast...).
**** *IPv6:*
Grâce à des adresses de *128 bits* /(au lieu de 32 bits en IPv4)/, on dispose d'un espace d'adressage bien plus important qu'IPv4 /(plus de 340 sextillions, ou *340*10^{36}* adresse différentes)/.

Cette quantité d'adresses considérable permet une plus grande *flexibilité* dans l'attribution des adresses et une meilleure agrégation des routes dans la table de routage d'Internet. La traduction d'adresse, qui a été rendue populaire par le manque d'adresses IPv4, n'est plus nécessaire.

Le *déploiement* d'IPv6 sur Internet est *compliqué* en raison de l'*incompatibilité* des adresses IPv4 et IPv6. Les traducteurs d'adresses automatiques se heurtent à des problèmes pratiques importants. Pendant une *phase de transition* où coexistent IPv6 et IPv4, les hôtes disposent d'une *double pile*, c'est-à-dire qu'ils disposent à la fois d'adresses IPv6 et IPv4, et des tunnels permettent de traverser les groupes de routeurs qui ne prennent pas encore en charge IPv6.
*** <<Serveur>>Serveur
*Ordinateur* équipé de logiciels lui permettant de *fournir des informations*, /comme des messages électroniques ou des pages web/, à d'autres [[Host][périphériques finaux]] sur le réseau.

CLIENT-------INTERNET-------SERVEUR
#+begin_quote
*Notes:* Chaque service nécessite un *logiciel serveur distinct*. Un seul ordinateur peut exécuter différents types de logiciel client.

\textcolor{luckydarkgray}{(Ex: Logiciel de serveur web pour offrir des services web. Un utilisateur peut vérifier son courrier électronique et consulter une page web tout en utilisant une messagerie instantanée et en écoutant un flux audio.)}
#+end_quote
** <<PeerToPeer>>Peer-To-Peer
Lorsqu'un *ordinateur* fait à la fois office de *serveur* et de *client* sur le réseau.

\textcolor{luckydarkgray}{(Ex: Réseaux particuliers, petites entreprises...)}
#+begin_quote
*Avantages:* 
\color{luckydarkgreen}
+ Facile à configurer
+ Moins complexe
+ Coût réduit car appareils réseau et serveurs dédiés pas toujours nécessaires
+ Peut-être utilisé pour des tâches simples
\color{black}
*Inconvénients:* 
\color{luckydarkred}
- Pas d'administration centralisée
- Peu sécurisé
- Non évolutif
- Tous les périphériques peuvent servir à la fois de client et de serveur, ce qui peut ralentir les performances.
\color{black}
#+end_quote
** Équipements actifs
*** <<PeripheriqueIntermediaire>>Périphérique intermédiaire
Périphérique *reliant* différents dispositifs finaux au réseau, et *fournissant la connectivité* en s'assurant que les données sont *transmises* sur le réseau.

\textcolor{luckydarkgray}{(Ex: Routeur, routeur sans fil, pare-feu, commutateur LAN, commutateur multicouche...)}
#+begin_quote
*Rôles:* 
- Régénérer et retransmettre les signaux de communications.
- Gérer des informations indiquant les chemins qui existent à travers le réseau et l'inter-réseau.
- Indiquer aux autres périphériques les erreurs et les échecs de communication.
- Diriger des données vers d'autres chemins en cas d'échec de liaison.
- Classifier et diriger des messages en fonction des priorités.
- Autoriser ou refuser le flux des données, selon des paramètres de sécurité.
#+end_quote
*Notes:* Tous les dispositifs intermédiaires remplissent la fonction de répéteur. Les dispositifs intermédiaires peuvent connecter plusieurs réseaux individuels pour former un inter-réseau.
*** <<Repeteur>>Répéteur
Dispositif qui *régénère et retransmet* les signaux de communication.
** <<SupportReseau>>Support réseau
*Canal* via lequel le *message se déplace* de la source à la destination.

Les plus connus sont:
- Le cuivre
- La fibre optique
- Les ondes électromagnétiques
\color{black}
#+begin_quote
\color{luckydarkgray}
Critères à prendre en compte:
- Distance maximale des supports
- Environnement
- Quantité de donnée et vitesse de transmission
- Coût des supports et de l'installation
#+end_quote
** <<DataCenter>>Data center (Centre de données)
Installation utilisée pour *héberger* les systèmes informatiques et les composants associés.
#+begin_quote
Un data center peut occuper une pièce d'un bâtiment, un ou plusieurs étages, voire même un bâtiment entier de la taille d'un entrepôt.

Sa construction et son entretien sont en général très coûteux, ainsi, les grandes entreprises utilisent des centres de données privés, alors que les entreprises de plus petite taille, qui n'ont pas le budget suffisant pour gérer leur propre data center privé, vont plutôt en louer.
#+end_quote
* Topologies et représentations du réseau
** Représentation du réseau
*** <<DiagrammeTopologie>>Diagramme de topologie
*Représentation visuelle* des connexions d'un réseau, permettant de comprendre facilement comment les appareils sont connectés dans ce réseau.
*** <<CarteInterface>>Carte d'interface (NIC)
*Relie physiquement* le dispositif terminal au réseau.
*** <<PortPhysique>>Port physique
*Connecteur* ou prise sur un dispositif de réseau où le support se connecte à un dispositif terminal ou à un autre dispositif de réseau.
*** <<Interface>>Interface
*Ports spécialisés* sur un dispositif de réseau qui se connecte à des réseaux individuels.
#+begin_quote
Comme les routeurs connectent les réseaux, les ports des routeurs sont appelés /interfaces réseaux/.

\textcolor{luckydarkgray}{Les termes port et interface sont souvent utilisés l'un pour l'autre.}
#+end_quote
* Types courants de réseaux
** Réseaux de tailles diverses
*** Petit réseau domestique
Relie *quelques ordinateurs* entre eux et à Internet.

\textcolor{luckydarkgray}{(Ex: Réseau classique familial)}
*** Réseau de petit bureau et de bureau à domicile (SOHO)
Permet aux ordinateurs d'un *bureau à domicile* ou d'un *bureau distant* de se connecter à un *réseau d'entreprise* ou d'accéder à des *ressources centralisées* et partagées.

\textcolor{luckydarkgray}{(Ex: Très petites entreprises)}
*** Moyen et grand réseaux
Possibilité d'avoir de *nombreux emplacements* avec des centaines ou des milliers d'hôtes inter-connectés.

\textcolor{luckydarkgray}{(Ex: Entreprises, écoles...)}
*** Réseau mondial
Connexion de *centaines de millions* d'ordinateurs dans le *monde entier*.

\textcolor{luckydarkgray}{(Ex: Internet)}
** LAN et WAN
*** <<LAN>>LAN (Local Area Network)
Un réseau local est une *infrastructure de réseau* qui fournit un accès aux utilisateurs et aux dispositifs finaux dans une *petite zone géographique*.

\textcolor{luckydarkgray}{(Ex: Maison, école, immeuble, campus...)}
#+begin_quote
*Caractéristiques:*
- Zone limitée
- Administré par une seule personne
- Bande passante à haut débit pour les périphériques terminaux internes et intermédiaires
#+end_quote
*** <<WLAN>>WLAN (Wireless Local Area Network)
Un WLAN est un [[LAN][LAN]] utilisant la technologie sans fil.
*** <<WAN>>WAN (World Area Network)
Un réseau mondial est une *infrastructure de réseau* qui donne accès à d'autres réseaux sur une *vaste zone géographique*, qui est généralement détenue et gérée par une grande entreprise ou un [[ISP][fournisseur de services de télécommunication]].
#+begin_quote
*Caractéristiques:*
- Vaste zone géographique \textcolor{luckydarkgray}{(Villes, états, provinces, pays, continents...)}
- Administré par plusieurs prestataires de services
- Liaisons à plus bas débit entre les réseaux locaux
#+end_quote
** <<Internet>>Internet
Ensemble *mondial* de [[Network][réseaux]] privés et publics inter-connectés. (Réseau de réseaux)
** Intranet et extranet
*** <<Intranet>>Intranet
Connexion *privée* de [[LAN][LAN]] et de [[WAN][WAN]] qui appartiennent à une organisation.
#+begin_quote
Il offre un accès aux membres de l'entreprise, à ses employés ou à d'autres personnes sous réserve d'une autorisation.
#+end_quote
*** <<Extranet>>Extranet
Accès sûr et sécurisé pour aux personnes qui travaillent pour une organisation différente, mais qui ont besoin d'accéder aux données de l'organisation.
#+begin_quote
\color{luckydarkgray}
Exemples:
- Entreprise qui donne accès aux fournisseurs et entrepreneurs de l'extérieur
- Hôpital qui fournit un système de réservation aux médecins afin qu'ils puissent prendre des rendez-vous pour leurs patients
- Bureau local de l'éducation qui fournit des informations sur le budget et le personnel aux écoles de son district
\color{black}
#+end_quote
#+begin_center
*\textcolor{luckydarkred}{INTERNET}-------\textcolor{luckydarkblue}{(EXTRANET)}-------\textcolor{luckydarkgreen}{((INTRANET))}*

\textcolor{luckydarkred}{Pas d'accès}--------\textcolor{luckydarkblue}{(Accès restreint)}------\textcolor{luckydarkgreen}{((Accès complet))}
#+end_center

* Connexions Internet
** Technologie d'accès à Internet
*** <<ISP>>ISP (Internet Service Provider)
*Fournisseur* d'accès à Internet. \textcolor{luckydarkgray}{(Ex: Proximus, Orange...)}
*** <<WISP>>WISP (Wireless Internet Service Provider)
Un WISP /(Wireless Internet Services Provider)/ est un [[ISP][fournisseur d'accès Internet]] qui connecte les abonnés à un point d'accès ou à un point d'échange désigné en utilisant des technologies *sans fil* similaires à celles que l'on trouve dans les [[WLAN][réseaux locaux sans fil]] des foyers.

Cette configuration n'est pas très différente de la technologie [[DSL][DSL]] ou du [[Cable][câble]]. La *principale différence* est la connexion entre le maison et l'ISP: Celle-ci se fait sans fil et n'utilise pas de câble.
** Connexions Internet des bureaux à domicile et des petits bureaux
*** <<Cable>>Câble
Utilisation du même câble que celui qui achemine la *télévision* par câble.
#+begin_quote
*Avantages:*
\color{luckydarkgreen}
- Large bande passante
- Connexion permanente à l'Internet
\color{black}
#+end_quote
*** <<DSL>>DSL (Digital Subscriber Line)
Utilisation d'une *ligne téléphonique*.
#+begin_quote
*Avantages:*
\color{luckydarkgreen}
- Large bande passante
- Connexion permanente à l'Internet
- Grande disponibilité
\color{black}
#+end_quote
**** <<ADSL>> *ADSL:*
/Asymmetric Digital Subscriber Line/

Vitesse descendante *supérieure* à la vitesse ascendante.
**** <<SDSL>> *SDSL:*
/Symmetric Digital Subscriber Line/

Vitesse descendante et ascendante *identiques* et élevées.

**** <<VDSL>> *VDSL:*
/Very high-speed rate Digital Subscriber Line/

Vitesse de transmissoin *très élevée*. \textcolor{luckydarkgray}{(Symmetric ou Asymmetric)}
*** <<Cellulaire>>Cellulaire
Utilisation d'un réseau de téléphonie *mobile*.
#+begin_quote
*Avantage:*

\textcolor{luckydarkgreen}{Permet une connexion dans une région qui, autrement, n'aurait aucune  connectivité Internet.}

*Inconvénient:*

\textcolor{luckydarkred}{Les antennes paraboliques nécessitent une ligne de vue claire vers le satellite.}
#+end_quote
*** <<LigneCommutee>>Ligne commutée
Utilisation d'une *ligne téléphonique* et d'un *modem*.
#+begin_quote
*Avantages:*
\color{luckydarkgreen}
- Peu coûteux
- Utile lors de déplacements
\color{black}
*Inconvénient:*

\textcolor{luckydarkred}{Faible bande passante, insuffisante pour les transferts de données importantes}
#+end_quote
** Connexion Internet d'entreprise
*** <<LigneLoueeDediee>>Ligne louées dédiée
Circuit *réservé* au sein du réseau du [[ISP][fournisseur de service]], qui relie des bureaux géographiquement séparés par un réseau privé de voix et/ou de données. (Généralement loué sur une base mensuelle ou annuelle)
*** <<Ethernet>>Ethernet (ou Ethernet WAN)
Étend la technologie d'accès [[LAN][LAN]] au [[WAN][WAN]].
*** <<BusinessDSL>>Business DSL
Souvent [[SDSL][SDSL]].
*** <<Satellite>>Satellite
Lorsqu'une solution câblée n'est pas disponible, on peut avoir recours à des satellites en orbite autour de la Terre, qui fournissent une connexion Internet sans fil.
** Réseau convergent
*** <<ReseauSepare>>Réseaux séparés traditionnels
Réseaux utilisant des *technologies différentes* pour le transport du signal de communication, et ne *pouvant donc pas communiquer entre eux*. 

Chaque réseau a son propre ensemble de règles et de normes pour garantir le bon fonctionnement des communications.

\textcolor{luckydarkgray}{(Ex: Les ordinateurs, téléphones, services de diffusion, ne peuvent pas communiquer entre eux. On ne peut donc pas voir un appel téléphonique sur un ordinateur)}
*** <<ReseauConvergent>>Réseaux convergents
Réseaux *capables de transmettre* des données, de la voix et de la vidéo entre de nombreux types d'*appareils différents* sur la même infrastructure de réseau. Cette infrastructure réseau utilise le même ensemble de /règles/, de /contrats/ et de /normes/ mis en oeuvre.

\textcolor{luckydarkgray}{(Ex: Les ordinateurs, téléphones, services de diffusion, peuvent communiquer entre eux grâce à une règle de contrat standard commune)}
* Réseaux fiables
** <<ArchitectureReseau>>Architecture réseau
Technologies qui soutiennent l'infrastructure et les services programmés et les règles, ou protocoles, qui font circuler les données sur le réseau.
** <<TolerancePannes>>Tolérance aux pannes
Limitation du nombre de dispositifs affectés lors d'une panne. Conception de façon à permettre une récupération rapide en cas de panne. Utilisation de la redondance.
*** <<Redondance>>Redondance
Utilisation de plusieurs chemins entre la source et la destination d'un message. Ainsi, si un chemin échoue, les messages sont instantanément envoyés sur un autre lien.
*** <<CommutationPaquets>>Commutation par paquets
*Fractionnement du trafic en /paquets/* qui sont acheminés sur un réseau partagé. Ainsi, un message unique (tel qu'un e-mail ou un flux vidéo) est fractionné en de nombreux blocs de messages appelés /paquets/, qui contiennent chacun les informations d'adressage nécessaires de la source et de la destination du message. Les routeurs du réseau commutent les paquets en fonction de l'état du réseau à ce moment là, ce qui signifie que *tous les paquets d'un même message peuvent emprunter des chemins très différents pour atteindre la même destination* car le routeur modifie dynamiquement l'itinéraire lorsqu'une connexion est défaillante (--> Redondance).
** Évolutivité
*** <<ReseauEvolutif>>Réseau évolutif
Un réseau évolutif se *développe rapidement* pour prendre en charge les nouveaux utilisateurs et applications, et ceci *sans dégrader les performances* des services auxquels les utilisateurs existant accèdent. En outre, les réseaux sont évolutifs étant donné que les concepteurs font *appel à des normes et à des protocoles reconnus*. Ainsi, les fournisseurs de logiciels et de matériel peuvent se concentrer sur l'amélioration des produits et des services, sans se soucier d'avoir à développer un nouvel ensemble de règles pour s'assurer leur fonctionnement dans le réseau.

\textcolor{luckydarkgray}{(Ex: Il est posible de connecter des utilisateurs supplémentaires, et même des réseaux entiers, à Internet, sans que les performances soient dégradés au niveau de l'utilisateur)}
** <<QoS>>Qualité de service (QoS)
Mécanisme essentiel pour *gérer l'encombrement* et assurer une fourniture fiable des contenus à l'ensemble des utilisateurs. Lorsque le volume du trafic est supérieur à ce qui peut être transporté sur le réseau, les appareils gardent les paquets en mémoire jusqu'à ce que des ressources soient disponibles pour les transmettre.

\textcolor{luckydarkgray}{(Ex: Si un utilisateur demande une page web, et un autre est au téléphone, lorsqu'une politique de QoS est mise en oeuvre, le routeur peut gérer le flux de données et le trafic voix en donnant la priorité aux communcations voix en cas de congestion du réseau)}

*Note:* Les pages web se voient généralement affecter une priorité moins élevée. Un appel de voix sur IP (VoIP) devra être prioritaire pour maintenir une expérience utilisateur fluide et ininterrompue.
*** <<Encombrement>>Encombrement
Lorsque la demande de bande passante excède la quantité disponible.
*** <<BandePassante>>Bande passante
Nombre de bits pouvant être transmis par seconde. (bit/s)
** <<SecuriteReseau>>Sécurité du réseau
Les administrateurs de réseaux doivent répondre à deux types de préoccupations en matière de sécurité des réseaux:
- La sécurité des infrastructures de réseau \textcolor{luckydarkgray}{(Sécurité physique)}
- La sécurité des informations \textcolor{luckydarkgray}{(Sécurité virtuelle)}

Il y a 3 exigences principales:
**** <<Confidentialité>> *Confidentialité:* Seuls les destinataires prévus et autorisés peuvent accéder aux données et les lire.
**** <<Integrite>> *Intégrité:* Garantir aux utilisateurs que les informations n'ont pas été altérées lors de leur transmission, de l'origine à la destination.
**** <<Disponibilite>> *Disponibilité:* Garantir aux utilisateurs un accès rapide et fiable aux services de données.
* Tendances des réseaux
Avec l'arrivée de nouvelles technologies et de nouveaux appareils sur le marché, les entreprises et les consommateurs doivent en permanence s'adapter à un environnement en constante évolution. Il existe plusieurs nouvelles tendances relatives au réseau qui vont affecter les entreprises et les consommateurs.
** <<BYOD>>BYOD (Bring Your Own Device)
Le BYOD donne aux utilisateurs finaux la liberté d'utiliser des outils personnels pour accéder aux informations et communiquer à travers un réseau d'entreprise ou de campus. C'est ce qu'on appelle le "Bring Your Own Device". \textcolor{luckydarkgray}{(--> "Apporte Ton Propre Appareil")}
** <<CollaborationEnLigne>>Collaboration en ligne
C'est le fait de travailler avec une ou plusieurs autres personnes sur un projet commun. Ceci offre un moyen de se connecter, d'interagir et d'atteindre des objectifs instantanément.
** <<CommunicationVideo>>Communication vidéo
Outil puissant pour communiquer avec d'autres utilisateurs à distance, tant u niveau régional qu'international. La vidéo devient une condition essentielle pour collaborer efficacement à mesure que les entreprises se développent au-delà des frontières géographiques et culturelles.
** <<CloudComputing>>Cloud computing
Le cloud computing nous permet de stocker des fichiers personnels, et même de sauvegarder un disque entier sur des serveurs via l'Internet, grâce aux [[DataCenter][centres de données]].

Il existe 4 principaux types de clouds:
**** <<CloudPublic>> *Cloud public*

Services mis à la disposition du grand public via Internet, pouvant être gratuits ou payants.
**** <<CloudPrive>> *Cloud privé*

Services destinés à une organisation ou une entité spécifique.
**** <<CloudHybride>> *Cloud hybride*

Constitué de deux ou plusieurs clouds, où chaque partie reste un objet distinct, mais où les deux sont reliés par une architecture unique. \textcolor{luckydarkgray}{(Ex: Une partie privée, et une partie publique)}
**** <<CloudCommunautes>> *Cloud de communautés*

Créé pour une utilisation exclusive par des entités ou des entreprises spécifiques, semblable à un environnement de cloud public, mais offrant les niveaux de sécurité, de confidentialité et de conformité réglementaire d'un cloud privé.
** <<TendanceTechnologiqueDomestique>>Tendances technologiques domestiques
Celles-ci n'affectent pas seulement la façon dont nous communiquons au travail et à l'école, mais elles modifient également de nombreux aspects de la maison. les dernières tendances pour la maison incluent les /technologies domestiques intelligents/.

*Technologies domestiques intelligentes:* Celles-ci s'intègrent dans les appareils ménagers quotidiens, qui peuvent ensuite se connecter à d'autres appareils pour les rendre plus /"intelligents"/ ou /automatisés/.

Les technologies domestiques intelligents sont en cours de développement et s'intègreront bientôt à toutes les pièces de la maison.

La technologie domestique intelligente deviendra de plus en plus courant à mesure que les réseaux domestiques et la technologie de l'Internet à haut débit se développeront.

\textcolor{luckydarkgray}{(Ex: Four programmable afin de déterminer certaines heures et températures en fonction de vos disponibilités et des aliments utilisés, avec possibilité de recevoir une notification sur un autre appareil lorsque le repas est prêt.}
** <<ReseauCourantElectrique>>Réseau sur courant électrique
Utilisation du *câblage électrique* existant pour connecter les appareils. Le réseau sur courant porteur transmet des informations en envoyant les données sur des *fréquences spécifiques*. Ainsi, les périphériques peuvent se connecter au [[LAN][LAN]] en utilisant n'importe quelle prise de courant.

Aucun câble de données n'a besoin d'être installé, et il y a peu (ou pas) d'électricité supplémentaire utilisée.

La mise en réseau par courant électrique n'est pas un substitut au câblage dédié dans les réseaux de données, toutefois, elle constitue une alternative lorsque les câbles de réseau de données ou les communications sans fil ne sont pas possibles ou efficaces.
** <<HautDebitSansFil>>Haut débit sans fil
Celle-ci utilise la même [[Cellulaire][technologie cellulaire]] qu'un téléphone intelligent. Une antenne est installée à l'extérieur de la maison pour offrir une connectivité avec ou *sans fil* aux périphériques à domicile.

Dans de nombreuses régions, le haut débit sans fil domestique est en concurrence avec la technologie [[DSL][DSL]] et le [[Cable][câble]].
* <<SecuriteReseau>>Sécurité du réseau
** <<MenacesSecurite>>Menaces de sécurité
La sécurité des réseaux fait partie intégrante des réseaux informatiques, que le réseau se trouve dans un foyer avec une seule connexion à l'Internet ou qu'il s'agisse d'une entreprise comptant des millions d'utilisateurs.

La sécurisation d'un réseau implique des protocoles, des technologies, des dispositifs, des outils et des techniques afin de protéger les données et d'*atténuer les menaces*. Ces risques ou menaces peuvent être *externes* ou *internes*.
*** Menaces internes
Violations par la faute d'utilisateurs *internes du réseau*.

En raison du développement des stratégies [[BYOD][BYOD]], les données d'entreprises sont beaucoup plus vulnérables.
#+begin_quote
\color{luckydarkgray}
Exemples:
- Perte ou vol d'un périphérique
- Mauvaise utilisation d'un périphérique
- Employé malveillant
\color{black}
#+end_quote
*** Menaces externes
Violations par la faute d'utilisateur *externes au réseau* (venant Internet).
**** <<Virus>> *Virus, vers et chevaux de Troie:*
Logiciels malveillants et code arbitraire s'exécutant sur un périphérique utilisateur.
**** <<Spyware>> *Spyware et adware:*
Types de logiciels installés sur l'appareil d'un utilisateur. Ce logiciel *recueille* alors secrètement des *informations* sur l'utilisateur.
**** <<JourZero>> *Attaques du jour zéro:*
Appelées aussi /attaques de l'heure zéro/, elles se produisent le *premier jour* où une vulnérabilité est connue.
**** <<ActeursMenace>> *Attaques des acteurs de menace:*
Une personne malveillante attaque les *appareils* des utilisateurs ou les *ressources* du réseau.
**** <<DoS>> *DoS (Denial of Service attack):*
Ces /attaques par déni de service/ *ralentissent* ou *bloquent* les applications et les processus sur un périphérique réseau.
**** *Interception et vol de données:*
Cette attaque permet de *capturer des informations privées* sur le réseau d'une organisation.
**** *Usurpation d'identité:*
Cette attaque consiste à *voler les identifiants* de connexion d'un utilisateur afin d'accéder à des données privées.
** <<SolutionsSecurite>>Solutions de sécurité
Il n'existe pas de solution unique capable de protéger le réseau contre toutes les menaces existantes. Pour cette raison, la sécurité doit être implémentée en *plusieurs couches* et faire appel à *plusieurs solutions* de sécurité.
*** Sécurité d'un réseau domestique
La mise en place de la /sécurité d'un réseau domestique/ est habituellement plutôt simple.

Généralement elle est implémentée sur les *appareils terminaux*, ainsi qu'au *point de connexion à l'Internet*, et on peut même compter sur les services contractuels d'[[ISP][ISP]].
**** <<Antivirus>> *Antivirus et antispyware:*
Ces applications aident à protéger les terminaux contre l'infection par des logiciels malveillants.
**** *Filtrage par pare-feu:*
Blocage des accès non autorisés à l'entrée et à la sortie du réseau. Il peut s'agir d'un système de [[Firewall][pare-feu]] basé sur l'hôte qui empêche tout accès non autorisé au dispositif final, ou d'un service de filtrage de base sur le routeur domestique pour empêcher tout accès non autorisé du monde extérieur vers le réseau.
*** Sécurité d'un réseau d'entreprise
La mise en place de la /sécurité d'un réseau d'entreprise/ implique généralement de *nombreux composants intégrés* dans le réseau afin de contrôler et de filtrer le trafic.

Les réseaux d'entreprises utilisent un antivirus, un antispyware et un filtrage de pare-feu, mais ils ont également d'autres exigences de sécurité:
**** *Systèmes de pare-feu dédiés:*
Ceux-ci offrent des capacités de [[Firewall][pare-feu]] plus avancées qui peuvent filtrer de *grandes quantités de trafic* avec une plus grande granularité.
**** <<ACL>> *ACL (Access Control List):*
Les listes de contrôle d'accès permettent de filtrer d'avantage l'accès et l'acheminement du trafic en fonction des [[IPAddress][adresses IP]] et des applications.
**** <<IPS>> *IPS (Intrusion Prevention System):*
Les /systèmes de prévention d'intrusion/ identifient les menaces qui se répandent rapidement, comme les attaques de type [[JourZero][jour zéro]].
**** *VPN:*
Les [[VPN][VPN]] fournissent un accès sécurisé à une organisation pour les travailleurs à distance.

* <<OS>>OS (Operating System)
Un /système d'exploitation/ est un ensemble de programmes qui dirige l'utilisation des ressources d'un ordinateur par des logiciels applicatifs.

Le système d'exploitation est le logiciel :
- Principal car il permet à l'ordinateur et aux programmes de fonctionner
- Qui se lance en second après le firmware (/programme d'amorçage/ ou /bootloader/) exécuté lors de la mise en marche de l'ordinateur.

Tous les *périphériques finaux* et *réseau* requièrent un /système d'exploitation/.
** Objectifs d'un OS
Les [[OS][OS]] réseau sont similaires aux OS d'un ordinateur classique.

Grâce à un [[GUI][GUI]], l'*OS d'un PC* permet à l'utilisateur de procéder aux opérations suivantes:
- Utiliser une souris pour faire des sélections ou exécuter des programmes
- Entrer des commandes textuelles
- Afficher des images sur un écran
Un *OS réseau* utilisant un [[CLI][CLI]] permet à un technicien réseau d'effectuer les opérations  suivantes:
- Utiliser un clavier pour exécuter des programmes réseau basés sur *CLI*
- Utiliser un clavier pour entrer des commandes textuelles
- Afficher des images sur un écran
** <<Kernel>>Kernel
Le /noyau/ d'un OS est sa partie qui assure la *communication* entre le *matériel* informatique et les *logiciels*, et qui gère le mode d'utilisation des ressources matérielles pour satisfaire la configuration logicielle.
** Interpréteur de commandes
L'/interpréteur de commandes/ d'un OS est un interface qui permet aux utilisateurs de demander des tâches spécifiques à partir de l'ordinateur. Ces requêtes peuvent être effectuées via l'interface *CLI* /(Command Line Interface)/ ou *GUI* /(Graphical User Interface)/.

Les *GUI* ne disposent pas toujours de toutes les fonctionnalités disponibles dans le *CLI*, et elles peuvent également tomber en panne ou simplement ne pas fonctionner correctement. C'est pourquoi l'accès aux périphériques réseau se fait habituellement vie le *CLI*.
* <<UI>>UI (User Interface)
** <<CLI>>CLI (Command Line Interface)
L'/interface en ligne de commande/ est le moyen *textuel* utilisé par les utilisateurs afin d'accéder à l'*interpréteur de commandes*.
#+begin_quote
Nécessite très *peu de ressources* pour fonctionner et offre une grande *stabilité* par rapport au *GUI*, cependant, l'utilisateur doit connaître la structure de commandes sous-jacente qui contrôle le système.
#+end_quote
** <<GUI>>GUI (Graphical User Interface)
L'/interface graphique/ permet aux utilisateurs d'interagir avec le système à l'aide d'un environnement utilisant des *éléments graphiques* /(icônes, menus, fenêtres...)/. \textcolor{luckydarkgray}{(Ex: Windows, MacOS, KDE...)}
#+begin_quote
Plus convivial que le *CLI* et ne nécessite pas de connaître la structure de commandes sous-jacente qui contrôle le système. En revanche, le *GUI* est moins fiable et plus lent que le *CLI*.
#+end_quote
* Méthodes d'accès
Un [[Switch][commutateur]] transmet le trafic par défaut et n'a *pas besoin* d'être explicitement configuré pour fonctionner.

\textcolor{luckydarkgray}{(Ex: Deux hôtes configurés connectés au même nouveau commutateur seraient en mesure de communiquer)}

Quel que soit le comportement par défaut d'un nouveau commutateur, *tous* les commutateurs doivent être *configurés* et *sécurisés*.
** <<AccesConsole>>Console
[[PortPhysique][Port]] de gestion permettant un accès *hors réseau* à un périphérique. L'accès hors bande désigne l'accès via un canal de gestion dédié qui est utilisé uniquement pour la maintenance des périphériques.

*Avantage:* \textcolor{luckydarkgreen}{Le périphériques est accessible même si aucun service réseau n'a été configuré.}
** <<SSH>>SSH (Secure Shell)
Moyen d'établir *à distance* une connexion [[CLI][CLI]] *sécurisée* via une interface virtuelle sur un réseau. Les connexions SSH requièrent des *services réseau actifs* sur le périphériques, notamment une interface active possédant une adresse.
** <<Telnet>>Telnet
Moyen *non sécurisé* d'établir une connexion [[CLI][CLI]] à distance via une interface virtuelle sur un réseau. Contrairement à /SSH/, /Telnet/ fournit une connexion qui n'est *pas sécurisée ni cryptée*, et ne doit donc être utilisé que dans un environnement de travaux pratiques.

Les informations d'authentification des utilisateurs, les mots de passe et les commandes sont envoyés sur le réseau *en clair*.
** <<EmulationTerminal>>Programmes d'émulation de terminal
Programme permettant de se *connecter* à un périphérique réseau via une connexion série sur un port de [[AccesConsole][console]] ou via une connexion [[SSH][SSH]] ou [[Telnet][Telnet]].

\textcolor{luckydarkgray}{(Ex: PuTTY, Tera Term, SecureCRT...)}

Ceux-ci permettent d'*améliorer la productivité* grâce à différentes fonctionnalités comme la *personnalisation* de la taille des fenêtres, de la taille des polices ou des jeux de couleurs.
* Utilisation de l'IOS de Cisco via le CLI
** Mode privilégié
Par mesure de sécurité, le logiciel Cisco IOS sépare l'accès à la gestion en deux modes de commande:
- Mode d'exécution *utilisateur* avec *accès limité* aux commandes \textcolor{luckydarkgray}{(Symbole '>')}
- Mode d'exécution *privilégié* avec *accès complet* aux commandes \textcolor{luckydarkgray}{(Symbole '\#')}
#+begin_quote
/Commande pour entrer en mode privilégié:/ =enable=.

/Commande pour revenir en mode utilisateur:/ =disable=.
#+end_quote
** Mode de configuration globale
Pour *configurer* un périphérique, l'utilisateur doit passer en mode de *configuration globale*. Celui-ci affecte le fonctionnement du périphérique dans son ensemble. Ce mode se reconnaît à l'invite de commande se terminant par *\text{(config)\#}* après le nom de l'appareil. \textcolor{luckydarkgray}{(Ex: Switch(config)\#)}

Une fois le mode de configuration globale activé, l'utilisateur a accès à des *sous-modes* de configuration. Les deux sous-modes de configuration les plus courants sont ceux-ci:
- Mode de configuration *en ligne* \textcolor{luckydarkgray}{(Via Console, SSH, Telnet ou AUX)}
- Mode de configuration d'*interface* \textcolor{luckydarkgray}{(Configuration de l'interface réseau d'un port de Switch ou routeur)}

Lors de l'utilisation d'un [[CLI][CLI]], le mode actif est reconnaissable à son invite de commandes unique.
#+begin_center
=Périphérique (mode-mode) mode=
#+end_center
\color{luckydarkgray}
Exemples:
- *\text{Switch(config-line)\#}* /= Configuration *en ligne* de *Switch* en mode *privilégié*/
- *\text{Foo(config-if)\#}* /= Configuration *interface* de *Foo* en mode *privilégié*/
\color{black}
#+begin_quote
/Commande pour entrer en mode de configuration globale:/ =configure terminal=.

/Commande pour sortir d'un mode de configuration:/ =exit=.

/Commande pour quitter tous les modes de configuration:/ =end= /ou/ =Ctrl+Z=.
#+end_quote
#+begin_quote
\color{luckydarkgray}Exemple:
- =Switch>=
- =Switch> enable=
- =Switch#=
- =Switch# configure terminal=
- =Switch(config)#=
- =Switch(config)# line console 0=
- =Switch(config-line)#=
- =Switch(config-line)# exit=
- =Switch(config)#=
- =Switch(config)# interface vlan 1=
- =Switch(config-if)#=
- =Switch(config-if)# end= /( ou/ =CTRL+Z= /)/
- =Switch#=
- =Switch# disable=
- =Switch>=
\color{black}
#+end_quote
** Structure des commandes IOS de base
Les commandes de base sont formées ainsi:
#+begin_center
\textcolor{luckydarkred}{Invite} + \textcolor{luckydarkgreen}{Commande} + \textcolor{luckydarkgray}{'espace'} + \textcolor{luckydarkblue}{Mot-clé ou argument}
#+end_center
#+begin_quote
\color{luckydarkgray}Exemples:
- \textcolor{luckydarkred}{Switch>} \textcolor{luckydarkgreen}{show} \textcolor{luckydarkblue}{ip protocol}
- \textcolor{luckydarkred}{Switch\#} \textcolor{luckydarkgreen}{ping} \textcolor{luckydarkblue}{192.168.10.5}
#+end_quote

Un *mot-clé* est un paramètre *spécifique* défini dans l'[[OS][OS]]. \textcolor{luckydarkgray}{(Ex: ip protocol)}

Un *argument* n'est pas défini dans l'OS, c'est une valeur ou variable définie par l'utilisateur. \textcolor{luckydarkgray}{(Ex: 192.168.10.5)}
** Conventions pour la configuration des noms d'hôte
Par convention, un nom d'hôte doit respecter les règles suivantes:
- Débuter par une lettre
- Ne pas contenir d'espaces
- Se terminer par une lettre ou un chiffre
- Ne comporter que des lettres, des chiffres et des tirets
- Comporter moins de 64 caractères

#+begin_quote
\color{luckydarkgray}
Exemple: (attribution du nom "=Sw-Floor-1=" au périphérique =Switch=)
- =Switch\# configure terminal=
- =Switch(config)\#=
- =Switch(config)\# hostname Sw-Floor-1=
- =Sw-Floor_1\#=
\color{black}
#+end_quote
** Configurer les mots de passe
Pour *sécuriser* l'accès en mode d'exécution *utilisateur*, il faut utiliser les commandes suivantes:
- =configure terminal= \textcolor{luckydarkgray}{(Entrer dans le mode de configuration globale)}
- =line console 0= \textcolor{luckydarkgray}{(Accéder à la première interface de la console de ligne, souvent la seule disponible)}
- =password azerty= \textcolor{luckydarkgray}{(Configurer le mot de passe "azerty")}
- =login= \textcolor{luckydarkgray}{(Activer l'accès d'exécution utilisateur)}
- =end= \textcolor{luckydarkgray}{(Quitter tous les modes de configuration)}

La console d'accès requiert à présent le mot de passe =azerty= avant d'accéder au mode d'exécution utilisateur.

Pour *sécuriser* l'accès en mode *privilégié*, il faut utiliser les commandes suivantes:
- =configure terminal= \textcolor{luckydarkgray}{(Entrer dans le mode de configuration globale)}
- =enable secret azerty= \textcolor{luckydarkgray}{(Configurer le mot de passe "azerty")}
- =exit= \textcolor{luckydarkgray}{(Quitter le mode de configuration)}

Les lignes *VTY* (virtual terminal) activent l'accès *à distance* au périphérique en utilisant [[SSH][SSH]] ou [[Telnet][Telnet]].

Pour sécuriser les lignes *VTY*,il faut utiliser les commandes suivantes:
- =configure terminal= \textcolor{luckydarkgray}{(Entrer dans le mode de configuration globale)}
- =line vty 0 15= \textcolor{luckydarkgray}{(Entrer dans le mode de configuration de VTY ligne)}
- =password azerty= \textcolor{luckydarkgray}{(Configurer le mot de passe "azerty")}
- =login= \textcolor{luckydarkgray}{(Activer l'accès VTY)}
- =end= \textcolor{luckydarkgray}{(Quitter tous les modes de configuration)}
** Chiffrer les mots de passe
Pour *chiffrer* tous les mots de passe en texte clair, il faut utiliser les commandes suivantes:
- =configure terminal= \textcolor{luckydarkgray}{(Entrer dans le mode de configuration globale)}
- =service password-encryption= \textcolor{luckydarkgray}{(Activer le chiffrement des mots de passe non chiffrés)}
- =end= \textcolor{luckydarkgray}{(Quitter le mode de configuration globale)}
- =show running-config= \textcolor{luckydarkgray}{(Vérifier que les mots de passe sont maintenant chiffrés)}
** Fichiers de configuration
*Deux fichiers* système stockent la *configuration* des périphériques:
- =startup config= \textcolor{luckydarkgray}{(Fichier stocké dans la mémoire non volatile, et donc, disponibles lors du démarrage de la machine)}
- =running-config= \textcolor{luckydarkgray}{(Fichier stocké dans la mémoire RAM, et donc, perdue lors de l'extinction de la machine)}
En cas de redémarrage ou de panne de courant, toutes les modifications de la configuration non enregistrées seront *perdues*.

Pour enregistrer les configurations dans le fichier "startup-config", il faut utiliser la commande suivant:
#+begin_center
=copy running-config startup-config=
#+end_center
Pour restaurer l'appareil dans sa configuration précédente (startup-config), il faut utiliser la commande suivante:
#+begin_center
=reload=

\textcolor{luckydarkgray}{(Cette commande impliquera une brève interruption du réseau)}
#+end_center
Pour supprimer toutes les configurations, il faut utiliser les commandes suivantes:
- =erase startup-config= \textcolor{luckydarkgray}{(Supprimer le fichier "startup-config")}

- =reload= \textcolor{luckydarkgray}{(Supprimer le fichier "running-config" et charger la configuration initiale d'origine)}
** Enregistrer une configuration dans un fichier texte
Pour *enregistrer* une configuration dans un *fichier texte*, il faut utiliser un [[EmulationTerminal][logiciel d'émulation de terminal]] \textcolor{luckydarkgray}{(Ex: PuTTY)} connecté à un [[Switch][Switch]].
- *Ouvrir* le logiciel d'émulation de terminal
- *Activer l'enregistrement* dans le logiciel d'émulation, et choisir un emplacement de fichier de sortie
- *Exécuter* la commande "=show running-config=" ou "=show startup-config=" dans l'invité de commande d'exécution privilégiée \textcolor{luckydarkgray}{(Le texte affiché dans la fenêtre du terminal est alors placé dans le fichier configuré à la deuxième étape)}
- *Désactiver l'enregistrement* dans le logiciel d'émulation

Pour *restaurer* un fichier de configuration sur un périphérique:
- Passer en mode de *configuration globale* sur le périphérique
- *Copier-Coller* le fichier texte dans la fenêtre du terminal connecté

\textcolor{luckydarkgray}{(Le texte contenu dans le fichier est appliqué sous forme de commandes dans l'environnement CLI et devient la configuration en cours du périphérique)}
** Configuration de l'interface de commutateur virtuelle
Pour accéder à distance au commutateur, une [[IPAddress][adresse IP]] et un [[SubnetMask][masque de sous-réseau]] doivent être configurés.

- =configure terminal= \textcolor{luckydarkgray}{(Accéder au mode de configuration global)}
- =interface vlan1= \textcolor{luckydarkgray}{(Accéder au mode de configuration interface de vlan1)}
- =ip address 192.168.1.20 255.255.255.0= \textcolor{luckydarkgray}{(Ex: Attribuer l'adresse IP en fonction du masque)}
- =no shutdown= \textcolor{luckydarkgray}{(Activer l'interface virtuelle)}
- =exit= \textcolor{luckydarkgray}{(Quitter le mode de config interface)}
- =ip default-gateway 192.168.1.1= \textcolor{luckydarkgray}{(Attribuer l'adresse IP à la passerelle par défaut)}
* Modèles et protocoles
** Exigences relatives au Protocole de Réseau
Les protocoles informatiques communs comprennent les exigences suivantes:
- Codage des messages
- Format et encapsulation des messages
- Taille des messages
- Synchronisation des messages
- Modes de transmission des messages
#+begin_quote
*Codage des messages:*

Il faut que l'[[Sender][expéditeur]] et la [[Destination][destination]] utilisent le même système de /codage/ et de /décodage/.

\textcolor{luckydarkgray}{(Ex: Si on veut dire quelque chose à quelqu'un, il vaut mieux utiliser une langue qu'il comprend)}

*Format et encapsulation des messages:*

Lorsqu'un message est envoyé de la source à la destination, il doit suivre un /format/ ou une /structure/ spécifique. Celui-ci dépend du type de message et du type de canal utilisé.

\textcolor{luckydarkgray}{(Ex: Si on veut envoyer un message à quelqu'un, on peut l'envoyer via une lettre par la poste. Celle-ci devra comporter l'adresse du destinataire placée au bon endroit, sans quoi la lettre ne sera pas transmise)}

*Taille des messages:*

Les informations transmises sur le réseau doivent avoir une taille bien spécifique. Il est donc nécessaire de séparer le message d'origine en plusieurs parties (fragmentation) afin de pouvoir transmettre un long message.

\color{luckydarkgray}(Ex: Si on envoie un SMS trop long, il sera envoyé en 2 SMS voir plus)\color{black}

*Synchronisation des messages:*

- Contrôle de flux: \textcolor{luckydarkgray}{Quantité d'informations qui peuvent être envoyées et la vitesse à laquelle elle peuvent être livrée}
- Délai de réponse: \textcolor{luckydarkgray}{Si aucune réponse n'a été reçue durant un certain délai, le message est considéré comme non transmis}
- Méthode d'accès: \textcolor{luckydarkgray}{Détermine le moment où un individu peut envoyer un message}

*Modes de transmission des messages:*

- Monodiffusion: \textcolor{luckydarkgray}{Informations transmises à un périphérique terminal unique}
- Multidiffusion: \textcolor{luckydarkgray}{Informations transmises à un ou plusieurs périphériques finaux}
- Diffusion: \textcolor{luckydarkgray}{Information transmise à tous les appareils finaux}
#+end_quote
** Types de protocoles
*** Protocoles de communications de réseaux
Permet à deux ou plusieurs périphériques de communiquer sur un ou plusieurs réseaux. \color{luckydarkgray}(Ex: TCP, HTTP...)\color{black}

*Fonctions:*

- Adressage: \textcolor{luckydarkgray}{Identification de l'expéditeur et du destinataire}
- Fiabilité: \textcolor{luckydarkgray}{Mécanismes de livraison garantis}
- Contrôle de flux: \textcolor{luckydarkgray}{Garantit que les données circulent à un rythme efficace}
- Séquençage: \textcolor{luckydarkgray}{Identification de manière unique chaque segment de données transmis (perte, retard, panne)}
- Détection des erreurs: \textcolor{luckydarkgray}{Détermine si les données ont été endommagées pendant la transmission}
- Interface de l'application: \textcolor{luckydarkgray}{Informations utilisées pour communications entre les applications réseaux}
*** Protocoles de sécurité des réseaux
Sécurise les données pour assurer l'authentification, l'intégrité des données et le cryptage des données. \color{luckydarkgray}(Ex: SSH, SSL, TLS...)\color{black}
*** Protocoles de routage
Permet aux routeurs d'échanger des informations de routage, de comparer les informations sur les chemins, puis sélectionner le meilleur chemin vers le réseau de destinations. \color{luckydarkgray}(Ex: OSPF, BGP...)\color{black}
*** Protocoles de découverte de services
Détection automatique des appareils ou des services. \color{luckydarkgray}(Ex: DHCP, DNS...)\color{black}
** Exemples de protocoles
*** HTTP (Hypertext Transfer Protocol)
Le protocole HTTP régit la manière dont un serveur web et un client web interagissent.

Il décrit le contenu et la mise en forme des requêtes et des réponses échangées entre le client et le serveur. Les logiciels du client et du serveur web implémentent le protocole HTTP dans le cadre de l'application. Le protocole HTTP dépend d'autres protocoles pour gérer le transport des messages entre le client et le serveur.
*** TCP (Transmission Control Protocol)
Le protocole TCP gère les conversations individuelles. TCP est responsable de garantir la livraison fiable des informations et de gérer le contrôle du flux entre les appareils finaux.
*** IP (Internet Protocol)
Le protocole IP est responsable de la remise des messages de l'expéditeur au destinataire. IP est utilisé par les routeurs pour transférer les messages sur plusieurs réseaux.
*** Ethernet
Le protocole Ethernet est responsable de la remise des messages d'une carte réseau à une autre carte réseau sur le même réseau local (LAN) Ethernet.
** Suites de protocoles
Une suite de protocole est un ensemble de protocoles qui fonctionnent ensemble pour fournir des services de communication réseau complets.
*** OSI (Protocole d'interconnexion de systèmes ouverts)
Il s'agit d'une suite de protocoles comprenant [[OSIModel][sept couches]] qui a été largement remplacée par TCP/IP aujourd'hui.
*** AppleTalk
Suite de protocoles propriétaire publiée par Apple en 1985 pour les appareils Apple, remplacée par TCP/IP en 1995.
*** Novell NetWare
Suite de protocoles propriétaire et système d'exploitation réseau développé par Novell en 1983 utilisant le protocole réseau IPX, remplacée par TCP/IP en 1995.
*** TCP/IP (Internet Protocol Suite)
Il s'agit de la suite de protocoles la plus courante et pertinente utilisée aujourd'hui. C'est une suite de protocoles standard ouverte gérée par Internet Engineering Task Force (IETF).

TCP/IP est la suite de protocoles utilisée par Internet et les réseaux aujourd'hui. Elle a deux aspects importants pour les fournisseurs et les fabricants:
- *Suite de protocoles standards ouverts:* Librement accessible au public et peut être utilisé par n'importe quel fournisseur sur son matériel ou dans son logiciel.
- *Suite de protocoles basée sur des normes:* Approuvée par le secteur des réseaux et par un organisme de normalisation. Les produits de différents fabriquant peuvent communiquer entre eux sans problème.
#+caption: Exemple des trois protocoles TCP/IP
#+attr_latex: :align c|c
| Nom de la couche | Pile de protocoles      |
|------------------+-------------------------|
| Application      | Protocole HTTP          |
| Transport        | Protocole TCP           |
| Internet         | Protocole IP            |
| Accès réseau     | Ethernet (ou autre)     |
** Protocoles couche d'application
*** Nom du système
**** *DNS (Domain Name System):*
#+begin_quote
Traduit les noms de domaine en adresses IP.
#+end_quote
*** Configuration hôte
**** *DHCPv4 (Dynamic Host Configuration Protocol version 4):*
#+begin_quote
Affecte dynamiquement les informations d'adressage IPv4 aux clients DHCPv4 au démarrage et permet de réutiliser les adresses lorsqu'elles ne sont plus nécessaires.

(Idem pour DHCPv6 mais adresses IPv6).
#+end_quote
**** *SLAAC (StateLess Address AutoConfiguration):*
#+begin_quote
Autoconfiguration des adresses apatrides. Permet à un périphérique d'obtenir ses informations d'adressage IPv6 sans utiliser un serveur DHCPv6.
#+end_quote
*** E-M@il
**** *SMTP (Simple Mail Transfer Protocol):*
#+begin_quote
Envoi de courriers électroniques.
#+end_quote
**** *POP3 (Post Office Protocol version 3):*
#+begin_quote
Récupérer le courrier électronique à partir d'un serveur de messagerie et téléchargement dans l'application de messagerie locale du client.
#+end_quote
**** *IMAP (Internet Message Access Protocol):*
#+begin_quote
Accès au courrier électronique stocké sur un serveur de messagerie et maintenance du courrier sur le serveur.
#+end_quote
*** Transfert de fichiers
**** *FTP (File Transfer Protocol):*
#+begin_quote
Accès et transfert de fichiers depuis un hôte vers un autre hôte via un réseau. Protocole fiable, connexion orienté et reconnu.
#+end_quote
**** *SFTP (SSH File Transfer Protocol):*
#+begin_quote
Session de transfert de fichiers sécurisée dans laquelle le transfert est crypté.
#+end_quote
**** *TFTP (Trivial File Transfer Protocol):*
#+begin_quote
Protocole simple et sans connexion avec livraison de fichiers sans accusé de réception. Produit moins de surcharge que FTP.
#+end_quote
*** Web et Service Web
**** *HTTP (HyperText Transfer Protocol):*
#+begin_quote
Ensemble de règles permettant d'échanger du texte, des graphiques, des sons, des vidéos et autres fichiers multimédia sur le Web.
#+end_quote
**** *HTTPS (HyperText Transfer Protocol Secure):*
#+begin_quote
Forme sécurisée de HTTP qui crypte les données échangées sur le World Wide Web.
#+end_quote
**** *REST (Representational State Transfer):*
#+begin_quote
Service Web qui utilise des interfaces de programmation dapplications (API) et des requêtes HTTP pour créer des applications Web.
#+end_quote
** Protocoles couche transport
*** Connexion orienté
**** *TCP (Transmission Control Protocol):*
#+begin_quote
Communication fiable entre des processus fonctionnant sur des hôtes distincts, transmissions fiables et reconnues qui confirment le succès de la livraison.
#+end_quote
*** Sans connexion
**** *UDP (User Datagram Protocol):*
#+begin_quote
Permet à un processus s'exécutant sur un hôte d'envoyer des paquets à un processus s'exécutant sur un autre hôte. Cependant l'UDP ne confirme pas la réussite de la transmission des datagrammes.
#+end_quote
** Protocoles couche internet
*** Protocole internet
**** *IPv4 (Internet Protocol version 4):*
#+begin_quote
Adresses codées sur 32 bits (décimal).

Reçoit des segments de la couche transport, emballe les messages en paquets et adresse les paquets pour une livraison de bout en bout sur un réseau.
#+end_quote
**** *IPv6 (Internet Protocol version 6):*
#+begin_quote
Pareil que IPv4 mais avec des adresses codées sur 128 bits (hexadécimal).
#+end_quote
**** *NAT (Network Address Traduction):*
#+begin_quote
Traduit les adresses IPv4 d'un réseau privé en adresse IPv4 publiques uniques au monde. (Permet de contourner le problème du manque d'adresses IPv4 différentes possibles par rapport au nombre de machines connectées).
#+end_quote
*** Envoi de messages
**** *ICMPv4 (Internet Control Message Protocol version 4):*
#+begin_quote
Fournit un retour d'information d'un hôte de destination à un hôte source sur les erreurs de livraison de paquets.
#+end_quote
**** *ICMPv6 (Internet Control Message Protocol version 6):*
#+begin_quote
Pareil que ICMPv4 mais pour les paquets IPv6.
#+end_quote
**** *ICMPv6 ND (Internet Control Message Protocol version 6 Neighbor Discovery):*
#+begin_quote
Inclut quatre messages de protocole utilisés pour la résolution d'adresses et la détection d'adresses en double.
#+end_quote
*** Protocoles de routage
**** *OSPF (Open Shortest Path First):*
#+begin_quote
Protocole de routage d'état de liaison qui utilise une conception hiérarchique basée sur des zones. (Ouvrez d'abord le chemin le plus court).
#+end_quote
**** *EIGRP (Enhanced Interior Gateway Routing Protocol):*
#+begin_quote
Protocole de routage propriétaire de Cisco qui utilise une métrique composite basée sur la largeur de la bande, le délai, la charge et la fiabilité.
#+end_quote
**** *BGP (Border Gateway Protocol):*
#+begin_quote
Protocole de routage de passerelle extérieure standard ouvert utilisé entre les [[ISP][ISPs]]. Également utilisé entre les ISPs et leurs clients privés plus importants pour échanger des informations de routage.
#+end_quote
** Protocoles couche réseau
*** Résolution d'adresse
**** *ARP (Address Resolution Protocol):*
#+begin_quote
Fournit un mappage d'adresse dynamique entre une adresse IPv4 et une adresse physique.
#+end_quote
*** Protocoles de liaison de données
**** *Ethernet:*
#+begin_quote
Définit les règles relatives aux normes de câblage et de signalisation de la couche d'accès au réseau.
#+end_quote
**** *WLAN (Wireless Local Area Network):*
#+begin_quote
Définit les règles de signalisation sans fil sur les fréquences radio 2.4GHz et 5.0GHz.
#+end_quote
** Encapsulation d'une donnée en TCP/IP
L'utilisateur va d'abord décider d'envoyer une certaine donnée.

#+caption: Données
#+attr_latex: :align |c| :placement [H]
|---------|
| Données |
|---------|

Ensuite On va ajouter une information =TCP= devant la =donnée=, c'est maintenant un =segment TCP=.

#+caption: Segment TCP
#+attr_latex: :align |c|c| :placement [H]
|-----+---------|
| TCP | Données |
|-----+---------|

On ajoute également une information =IP= devant =TCP=, on a maintenant un =paquet IP=.

#+caption: Paquet IP
#+attr_latex: :align |c|c|c| :placement [H]
|----+-----+---------|
| IP | TCP | Données |
|----+-----+---------|

Enfin, on ajoute une donnée =Ethernet= devant =IP= et également une info à la fin, et on obtient une =trame Ethernet=.

#+caption: Trame Ethernet
#+attr_latex: :align |c|c|c|c|c| :placement [H]
|----------+----+-----+---------+---|
| Ethernet | IP | TCP | Données | i |
|----------+----+-----+---------+---|
** Normes
Il existe de nombreux fabricants différents de composants réseau, ils doivent donc tous utiliser les mêmes normes afin d'être compatibles.

Les normes sont élaborées par des organismes internationaux de normalisation.
*** Normes Internet
#+caption: Organismes de normalisation Internet
#+attr_latex: :width 300px :placement [H]
file:Pictures/NormesInternet.png
**** *ISOC (Internet Society):*
#+begin_quote
Responsable de la promotion du développement ouvert et de l'évolution de l'utilisation de l'Internet dans le monde entier.
#+end_quote
**** *IAB (Internet Architecture Board):*
#+begin_quote
Responsable de la gestion globale et du développement des normes Internet.
#+end_quote
**** *IETF (Internet Engineering Task Force):*
#+begin_quote
Développe, met à jour et assure la maintenance des technologies Internet.
#+end_quote
**** *IRTF (Internet Research Task Force):*
#+begin_quote
Se concentre sur la recherche à long terme liée à l'Internet et aux protocoles TCP/IP comme l'Anti-Spam research Group (ASRG), le Crypto Forum Research Group (CFRG) et le Peer-to-Peer Research Group (P2PRG).
#+end_quote
**** *Organismes de normalisation impliqués dans le développement et le soutien du TCP/IP:*
#+caption: Organismes de normalisation TCP/IP
#+attr_latex: :width 300px :placement [H]
file:Pictures/IANAICANN.png
**** *ICANN (Internet Corporation for Assigned Names and Numbers):*
#+begin_quote
Basée aux États-Unis, l'ICANN coordonne l'attribution des adresses IP, la gestion des noms de domaine et l'attribution d'autres informations utilisées dans les protocoles TCP/IP.
#+end_quote
**** *IANA (Internet Assigned Numbers Authority):*
#+begin_quote
Responsable de la supervision et de la gestion de l'attribution des adresses IP, de la gestion des noms de domaine et des identificateurs de protocole pour l'ICANN.
#+end_quote
* TODO Suite en cours de création...
* Vocabulaire de base
** <<OSIModel>>OSI Model (Open Systems Interconnection)
Le modèle OSI est une *norme de communication*, en réseau, de tous les systèmes informatiques. C'est un modèle de communications entre ordinateurs proposé par l'ISO (Organisation internationale de normalisation) qui décrit les fonctionnalités nécessaires à la communication et l'organisation de ces fonctions.
#+caption: Modèle OSI [[https://fr.wikipedia.org/wiki/Mod%C3%A8le_OSI#Architecture_en_couches][(Wikipédia)]]
file:Pictures/ModelOSI-Schema.png
** <<Protocol>>Protocol
Ensemble de *règles* qui régissent les *échanges de données* ou le comportement collectif de processus ou d'ordinateurs en réseaux ou d'objets connectés.
#+begin_quote
\color{luckydarkgray}
Exemple de protocole si on veut discuter avec quelqu'un:

- On l'appelle pour savoir s'il est attentif et prêt à discuter
- On attend sa réponse pour savoir si on peut commencer la discussion
- On parle, en se répondant mutuellement à chaque phrase
- En cas de non réponse à une phrase, on peut lui demander s'il est attentif
- On précise que l'on va devoir mettre fin à la discussion
- On lui dit au revoir en partant, pour mettre fin la discussion
\color{black}
#+end_quote
** <<UploadDownload>>Téléchargement ascendant/descendant
**** *Ascendant:* Envoi de données. \textcolor{luckydarkgray}{(Upload)}
**** *Descendant:* Réception de données. \textcolor{luckydarkgray}{(Download)}

** <<Sender>>Sender (Expéditeur)
Source de l'information. Celui qui envoie le message.
** <<Destination>>Destination
Celui qui reçoit le message et l'interprète.
** <<Canal>>Canal
Support qui assure le cheminement du message de la source à la destination.
** <<Paquet>>Packet
Afin de transmettre un message d'une machine à une autre sur un réseau, celui-ci est *découpé* en plusieurs paquets transmis séparément.

Un paquet inclut un en-tête (en anglais, header), comprenant les informations nécessaires pour acheminer et reconstituer le message, et encapsule une partie des données. \textcolor{luckydarkgray}{(Ex: Le paquet IP)}

Le paquet ne doit pas être confondu avec la [[Frame][trame]], correspondant à la couche liaison (couche 2 du [[OSIModel][modèle OSI]]). \textcolor{luckydarkgray}{(Ex: la trame Ethernet)}
** <<Frame>>Frame
Dans les réseaux informatiques, une /trame/ est la *structure de base* d'un ensemble de données encadré par des bits de début /(drapeau)/ et des bits de fin /(fanion)/.

Une trame est composée

- D'un *header* /(en-tête)/
- Des *données* que l'on veut transmettre
- D'un *trailer* /(postambule)/. Un [[Paquet][paquet]] (dans le cas d'IP par exemple) ne peut transiter directement sur un réseau : il est *encapsulé* comme données à l'intérieur d'une /trame/ qui elle-même finit en un *enchaînement de bits* qui circule sur le support physique

Il existe trois versions différentes (dont une qui a été abandonnée):

**** +Ethernet Type I (créée par Xerox) abandonnée à l'heure actuelle+
**** Ethernet Type II (propriétaire Intel, Digital, Xerox)
**** IEEE 802.3.

** <<MACAddress>>MAC (Media Access Control)
Une /adresse MAC/, parfois nommée *adresse physique*, est un *identifiant physique* et *unique au monde*, stocké dans une *carte réseau* ou une interface réseau similaire.

*Toutes* les cartes réseau ont une adresse MAC, même celles contenues dans les PC et autres appareils connectés. \textcolor{luckydarkgray}{(Ex: Tablette tactile, smartphone, consoles de jeux, réfrigérateurs, montres ...)}

Une *adresse MAC-48* est constituée de *48 bits* /(6 octets)/ et est généralement représentée sous la forme *hexadécimale* en séparant les octets par un double point. \textcolor{luckydarkgray}{(Ex: 5E:FF:56:A2:AF:15)}
#+begin_quote
*Ces 48 bits sont répartis de la façon suivante:*
- *1 bit* I/G : indique si l'adresse est individuelle, auquel cas le bit sera à 0 (pour une machine unique, unicast) ou de groupe (multicast ou broadcast), en passant le bit à 1
- *1 bit* U/L : 0 indique si l'adresse est universelle (conforme au format de l'IEEE) ou locale, 1 pour une adresse administrée localement
- *22 bits* réservés : tous les bits sont à zéro pour une adresse locale, sinon ils contiennent l'adresse du constructeur
- *24 bits* : adresse unique (pour différencier les différentes cartes réseaux d'un même constructeur)
#+end_quote
Les concepteurs d'Ethernet ayant utilisé un adressage de 48 bits, il existe potentiellement 2^{48} d'adresses MAC possibles /(environ 281 000 milliards)/. L'IEEE donne des préfixes de 24 bits (appelés Organizationally Unique Identifier - OUI) aux fabricants, ce qui offre 2^{24} d'adresses MAC disponibles par préfixe /(environ 16 millions)/.
** <<SubnetMask>>Subnet mask
Le /masque de sous réseau/ est le masque distinguant les *bits* d'une [[IPAddress][adresse IPv4]] utilisés pour identifier le *sous-réseau* de ceux utilisés pour identifier l'[[Host][hôte]]. L'adresse du *sous-réseau* est obtenue en appliquant l'*opérateur* =ET= binaire entre l'adresse IPv4 et le /masque de sous-réseau/. L'adresse de l'hôte à l'intérieur du sous-réseau est quant à elle obtenue en appliquant l'*opérateur* =ET= entre l'adresse IPv4 et le *complément à un* du masque.

Un masque de sous réseau ne pourra donc *jamais* être composé d'un =0= suivi d'un =1=. Uniquement une suite de =1= suivie d'une suite de =0=.

(+=0.250.250.250=+ n'est *pas* un masque de sous réseau valide, par contre =250.250.250.0= est valide)
#+begin_quote
\color{luckydarkgray}
Exemple:
#+attr_latex: :align c|c|c|c
|--------------------------+-----------------+---------------+-------------------------------------------|
| /Adresse IPv4/           | =192.168.1.2=   | =192.168.1.2= | /Adresse IPv4/                            |
| /&/                      | =&=             | =&=           | /&/                                       |
| /Masque de sous réseau/  | =255.255.255.0= | =0.0.0.255=   | /Complément à 1 du masque de sous réseau/ |
|--------------------------+-----------------+---------------+-------------------------------------------|
| /=/                      | ===             | ===           | /=/                                       |
| /Adresse de sous réseau/ | =192.168.1.0=   | =0.0.0.2=     | /Adresse de l'hôte dans le sous réseau/   |
|--------------------------+-----------------+---------------+-------------------------------------------|

||
Soit en binaire:

#+attr_latex: :align |c|c|
|---------------------------------------+---------------------------------------|
| =11000000.10101000.00000001.00000010= | =11000000.10101000.00000001.00000010= |
| =&=                                   | =&=                                   |
| =11111111.11111111.11111111.00000000= | =00000000.00000000.00000000.11111111= |
|---------------------------------------+---------------------------------------|
| ===                                   | ===                                   |
| =11000000.10101000.00000001.00000000= | =00000000.00000000.00000000.00000010= |
|---------------------------------------+---------------------------------------|
#+end_quote
** <<Routing>>Routing
Le /routage/ est le *mécanisme* par lequel des *chemins* sont *sélectionnés* dans un réseau pour acheminer les données d'un expéditeur jusqu'à un ou plusieurs destinataires. Le /routage/ est une tâche exécutée dans de nombreux réseaux, tels que le réseau téléphonique, les réseaux de données électroniques comme Internet, et les réseaux de transports. Sa performance est importante dans les réseaux décentralisés, c'est-à-dire où l'information n'est pas distribuée par une seule source, mais échangée entre des agents indépendants. C’est grâce à ça que par exemple les mails sont envoyés aux bons destinataires.
*** <<Unicast>>Unicast
#+attr_latex: :width 50px :center nil
file:Pictures/Unicast-Schema.png Il n'existe qu'*une association* entre une adresse réseau et le *point d'arrivée final* : chaque adresse de destination identifie de manière unique *un seul receveur final*.
*** <<Anycast>>Anycast
#+attr_latex: :width 50px :center nil
file:Pictures/Anycast-Schema.png Technique d'adressage et de routage permettant de rediriger les données vers le serveur informatique le « *plus proche* » ou le « *plus efficace* » selon la politique de routage.
*** <<Multicast>>Multicast
#+attr_latex: :width 50px :center nil
file:Pictures/Multicast-Schema.png Forme de diffusion d'un émetteur (source unique) vers un *groupe de récepteurs*. Les termes /diffusion multipoint/ ou /diffusion de groupe/ sont également employés.

Les récepteurs intéressés par les messages adressés à ce groupe doivent s'inscrire à ce groupe. Ces abonnements permettent aux switchs et routeurs intermédiaires d'établir une route depuis le ou les émetteurs de ce groupe vers les récepteurs de ce groupe.
#+begin_quote
*Avantages:*
\color{luckydarkgreen}
- Plus efficace que l'unicast pour diffuser des contenus simultanément vers une large audience. En streaming unicast, on enverrait l'information autant de fois qu'il y a de connexions, d'où gaspillage de temps, de ressources du serveur et surtout de bande passante. Au contraire, en multicast, chaque paquet n'est émis qu'une seule fois et sera routé vers toutes les machines du groupe de diffusion sans que le contenu ne soit dupliqué sur une quelconque ligne physique
- Le multicast permet de développer des applications interactives de groupe, comme la visioconférence, le partage de tableau...
\color{black}
*Inconvénients:*
\color{luckydarkred}
- Ne permet pas le contrôle de la participation au groupe par la source : la source ne peut déterminer ni qui participe, ni qui peut participer ou non au groupe
- L'identification et l'authentification des participants doivent être prises en charge au niveau applicatif si elles sont souhaitées
\color{black}
#+end_quote
*** <<Broadcast>>Broadcast
#+attr_latex: :width 50px :center nil
file:Pictures/Broadcast-Schema.png Technique d'adressage et de routage permettant de rediriger les données vers *toutes* les machines connectées au réseau.
** <<Firewall>>Firewall
Un pare-feu est un logiciel et/ou un matériel permettant de faire respecter la politique de sécurité du réseau, celle-ci définissant quels sont les types de communications autorisés sur ce réseau informatique. Il surveille et contrôle les applications et les flux de données ([[Paquet][paquets]]). 
** <<Gateway>>Gateway
Une /passerelle/ est le nom générique d'un dispositif permettant de *relier* deux réseaux informatiques de types différents. \textcolor{luckydarkgray}{(Ex: Un réseau local et le réseau Internet)}
** <<HUB>>HUB
Un /concentrateur Ethernet/ est un appareil informatique permettant de *concentrer* les transmissions Ethernet de plusieurs équipements sur un même support dans un réseau informatique local.

Ce dispositif est un *répéteur de données* ne permettant *pas de protection* particulière des données et transmettant les [[Frame][trames]] à toutes les machines connectées (par opposition au [[Switch][commutateur réseau]] qui dirige les données uniquement vers la machine destinataire). Ceci le rend *vulnérable aux attaques* par Analyseur de paquets. Il permet également d'étendre un [[LAN][réseau local]] mais ne permet pas de le transformer en un [[WAN][réseau étendu]].

Le /HUB/ possède deux types de [[PortPhysique][ports]]:
- Les ports pour la connexion des machines
- Le port pour extension du réseau auquel se connecte un autre concentrateur (il n'y en a généralement qu'un seul par concentrateur). Ce type de port est identique au précédent à l'exception du câblage qui est inversé (on peut aussi utiliser un câble à connecteur RJ45 croisé pour y connecter un ordinateur supplémentaire).
** <<Switch>>Switch
Un /commutateur réseau/ est un équipement qui *relie* plusieurs segments (câbles ou fibres) dans un *réseau* informatique et de télécommunication et qui permet de créer des *circuits virtuels*.

La /commutation/ est un des deux modes de transport de trame au sein des réseaux informatiques et de communication, l'autre étant le *routage*. Dans les [[LAN][réseaux locaux]], il s'agit le plus souvent d'un boîtier disposant de plusieurs ports RJ45 (entre 4 et plusieurs centaines), il a donc la même apparence qu'un [[HUB][concentrateur]].

Contrairement à un [[HUB][concentrateur]], un /commutateur/ ne reproduit pas sur tous les ports chaque trame qu'il reçoit : il sait *déterminer sur quel port* il doit envoyer une [[Frame][trame]], en fonction de l'*adresse de destination* de cette *trame*. Les commutateurs sont souvent utilisés pour remplacer des [[HUB][concentrateurs]] car *ils encombrent moins le réseau*.

#+begin_quote
*Fonctionnement:*

Le /commutateur/ établit et met à jour une *table*, dans le cas du /commutateur/ pour un réseau [[Ethernet][Ethernet]] il s'agit de la *table d'adresses MAC*, qui lui indique sur quels ports diriger les [[Frame][trames]] destinées à une [[MACAddress][adresse MAC]] donnée, en fonction des adresses MAC source des trames reçues sur chaque [[PortPhysique][port]]. Le commutateur *construit* donc dynamiquement une *table* qui associe numéro de port et adresses MAC. 
#+end_quote
** <<DDoS>>DDoS (Distributed Denial of Service attack)
Une /attaque par déni de service/ (DoS) est une attaque informatique ayant pour but de rendre indisponible un service, d'empêcher les utilisateurs légitimes d'un service de l'utiliser. À l’heure actuelle la grande majorité de ces attaques se font à partir de *plusieurs sources*, on parle alors d'*attaque par déni de service distribuée (DDoS)*.

Il peut s'agir de :

- L’inondation d’un réseau afin d'empêcher son fonctionnement
- La perturbation des connexions entre deux machines, empêchant l'accès à un service particulier
- L'obstruction d'accès à un service pour une personne en particulier
- Le fait d'envoyer des milliards d'octets à une box internet

L'/attaque par déni de service/ peut ainsi *bloquer un serveur* de fichiers, rendre impossible l'accès à un serveur web ou empêcher la distribution de courriel dans une entreprise. 
** <<VPN>>VPN (Virtual Private Network)
Le /réseau privé virtuel/ est un système permettant de créer un *lien direct* entre des ordinateurs distants, qui *isole* leurs échanges du reste du trafic se déroulant sur des réseaux de télécommunication publics. 

**** Un VPN permet d'accéder à des ordinateurs distants comme si l'on était connecté au réseau local. Il permet d'avoir un *accès au réseau interne* (réseau d'entreprise, par exemple) ou de créer un *réseau de pairs*.

**** Un VPN dispose généralement aussi d'une [[Gateway][passerelle]] permettant d'accéder à l'extérieur, ce qui permet de *changer l'adresse IP source* apparente de ses connexions. Cela rend plus difficile l'identification et la localisation approximative de l'ordinateur émetteur par le fournisseur de service. Cela permet aussi de contourner les restrictions géographiques de certains services proposés sur Internet. L'utilisation des VPN n'est généralement pas légalement restreinte (sauf en Chine).

Cependant, l'infrastructure de VPN (généralement un serveur) dispose des informations permettant d'identifier l'utilisateur. \textcolor{luckydarkgray}{(Ex: Les sociétés proposant des VPN gratuits ou payants peuvent récolter les données de navigation de leurs clients, ce qui relativise l'anonymat de ces services)}

**** Le VPN permet également de construire des *réseaux overlay*, en construisant un *réseau logique* sur un *réseau sous-jacent*, faisant ainsi abstraction de la topologie de ce dernier. 
